<?php

return [
    'id' => [
        'about_detail' => [
            'positioning_label' => 'About & Positioning',
            'positioning_title' => 'Delivery lokal dengan standar enterprise dan dukungan regional.',
            'positioning_body' => [
                'Nakala Digital berperan sebagai mitra delivery dan client-facing berbasis Indonesia untuk organisasi yang membutuhkan AI technology, custom software development, dan solusi digital yang siap digunakan.',
                'Kami menggabungkan standar delivery enterprise dengan pemahaman pasar lokal, sehingga produk yang dibangun tetap scalable, praktis, dan relevan untuk kebutuhan operasional Indonesia.',
            ],
            'romulus_note' => 'Melalui strategic partnership dengan Romulus Digital, Nakala Digital mendapat dukungan kapabilitas regional di AI SaaS, Microsoft D365, cloud applications, Experience-Led Design, dan Resources as a Service.',
        ],
        'why_details' => [
            ['title' => 'Local Delivery, Regional Reach', 'body' => 'Tim berbasis Indonesia dengan dukungan teknologi regional dari network Romulus Digital.'],
            ['title' => 'AI-Enabled Mindset', 'body' => 'AI automation dan intelligent workflow dimasukkan saat benar-benar memberi nilai operasional.'],
            ['title' => 'Agile Delivery & QA Governance', 'body' => 'Sprint delivery, backlog management, SIT/UAT, dokumentasi, dan release gate dijaga sejak awal.'],
            ['title' => 'Experience-Led Design', 'body' => 'Desain dibangun dari user journey dan proses bisnis, bukan hanya dari sisi teknologi.'],
            ['title' => 'Practical & Impact-Driven', 'body' => 'Solusi dirancang agar scalable, mudah dioperasikan, dan punya outcome bisnis yang terukur.'],
            ['title' => 'Strategic Partner Network', 'body' => 'Kapasitas engineer, designer, QA, cloud, dan Microsoft specialist dapat diskalakan sesuai kebutuhan proyek.'],
        ],
        'service_pillar_details' => [
            ['title' => 'AI Technology & GenAI', 'body' => 'Intelligent automation, GenAI applications, AI-powered recruitment, coaching, dan decision support system.'],
            ['title' => 'Custom Software Development', 'body' => 'Web apps, mobile apps, SaaS platforms, dan enterprise systems yang dibangun sesuai kebutuhan.'],
            ['title' => 'Technology Consulting', 'body' => 'Business and technology alignment, solution roadmap, requirements, governance, dan strategic advisory.'],
            ['title' => 'Web & Portal Development', 'body' => 'Corporate website, CMS, e-commerce, public-facing portal, dan platform edukasi.'],
            ['title' => 'QA Governance & Testing', 'body' => 'End-to-end QA, SIT/UAT, test planning, release governance, dan dokumentasi acceptance.'],
            ['title' => 'Managed Support & D365', 'body' => 'Post-launch support, Microsoft D365 Finance assistance, Power Platform, dan managed services.'],
        ],
        'ai_capability_details' => [
            ['title' => 'GenAI Applications', 'body' => 'Conversational AI, document intelligence, dan workflow berbantuan LLM.'],
            ['title' => 'AI Hiring & Recruitment', 'body' => 'CV parsing, candidate scoring, interview scheduling, talent analytics, dan shortlisting otomatis.'],
            ['title' => 'AI Coaching Platforms', 'body' => 'Digital coaching assistant, personalized learning path, goal tracking, dan progress dashboard.'],
            ['title' => 'Intelligent Automation', 'body' => 'Automasi proses, smart notification, dan trigger operasional berbasis AI.'],
            ['title' => 'AI SaaS Platform Development', 'body' => 'Pengembangan produk AI SaaS end-to-end untuk B2B dan enterprise market.'],
            ['title' => 'Data & Analytics Integration', 'body' => 'Dashboard intelligence, reporting automation, dan data pipeline development.'],
            ['title' => 'Microsoft Power Platform', 'body' => 'Integrasi Power BI, Power Automate, dan AI Builder untuk kebutuhan enterprise.'],
            ['title' => 'Strategic AI Advisory', 'body' => 'AI readiness assessment, use case identification, dan implementation roadmap.'],
        ],
        'solution_details' => [
            ['title' => 'Web Application Development', 'body' => 'Responsive web apps dengan modern framework, performa baik, dan API-first architecture.'],
            ['title' => 'HRIS / HSE / Operational Platforms', 'body' => 'Platform HR, safety, dan operations management untuk lingkungan bisnis Indonesia.'],
            ['title' => 'School & Education Portals', 'body' => 'PPDB system, academic portal, dan digital school platform untuk yayasan serta institusi pendidikan.'],
            ['title' => 'API & System Integration', 'body' => 'Integrasi secure API untuk menghubungkan tools, third-party services, dan legacy systems.'],
        ],
        'solution_highlights' => [
            'Customer Engagement & Customer Profiling',
            'Omnichannel Commerce: POS, WMS, OMS, Loyalty, and SAP Integration',
            'LMS & Parent Experience with AI Support',
            'MoneyKu - Accounting and Small Business Management',
            'VMS - Vendor Management System',
            'OSMS - Operational Security Management System',
            'Digital Cooperative and Local Government Solutions',
            'BGN / SPPG Operational Support',
            'HRMS and HSE Platforms',
            'Web Portal and WargaKas',
            'AI Hiring and Recruitment',
            'Digital Coaching and AI Coach Platform',
        ],
        'model_details' => [
            [
                'title' => 'Consulting & Strategy',
                'body' => 'Membantu menentukan arah transformasi, arsitektur solusi, pengalaman pengguna, dan kesiapan AI sebelum build dimulai.',
                'items' => [
                    'Technology consulting dan digital transformation roadmap',
                    'Experience-led design, UX research, wireframe, dan product flow',
                    'AI readiness assessment dan identifikasi use case berdampak tinggi',
                ],
            ],
            [
                'title' => 'Build & Develop',
                'body' => 'Mengubah scope menjadi produk digital yang usable melalui software development, AI platform, dan operational system.',
                'items' => [
                    'Custom software, web apps, mobile apps, SaaS, dan enterprise system',
                    'AI & GenAI platform seperti AI Hiring, AI Coaching, dan document intelligence',
                    'Operational systems untuk HRMS, HSE, cash management, dan kebutuhan industri',
                ],
            ],
            [
                'title' => 'Run & Support',
                'body' => 'Menjaga kualitas release dan keberlanjutan produk lewat QA governance, support, D365, dan continuous improvement.',
                'items' => [
                    'SIT/UAT, release governance, test report, dan BAST documentation',
                    'Post-launch maintenance, bug fixing, dan improvement request',
                    'D365 Finance support, Power Platform integration, dan Resources as a Service',
                ],
            ],
        ],
        'delivery_notes' => [
            ['title' => 'Artefak delivery', 'body' => 'Product backlog, sprint plan, sprint review notes, SIT/UAT documentation, handover package, dan BAST.'],
            ['title' => 'Continuous improvement', 'body' => 'Post-go-live retrospective dan structured improvement cycle disiapkan agar setiap iterasi makin baik.'],
        ],
        'qa_governance' => [
            ['title' => 'Requirement Review', 'body' => 'Functional dan non-functional requirement divalidasi sebelum development dimulai.'],
            ['title' => 'Test Planning & SIT/UAT', 'body' => 'Test case, scenario coverage, dan user acceptance testing dibuat secara terstruktur bersama client.'],
            ['title' => 'Bug Tracking & Release Readiness', 'body' => 'Issue log, severity classification, resolution tracking, dan go/no-go release gate dikelola jelas.'],
            ['title' => 'BAST, Handover & Warranty', 'body' => 'Acceptance documentation, knowledge transfer, dan warranty support disiapkan untuk transisi produksi.'],
        ],
        'portfolio' => [
            'subtitle' => 'Case study yang lebih detail dari challenge sampai capability dan impact.',
            'features' => 'Key Features',
            'capability' => 'Relevant Capability',
            'business_impact' => 'Business Impact',
        ],
        'portfolio_items' => [
            [
                'subtitle' => 'Education Digital Transformation',
                'challenge' => 'Institusi pendidikan masih mengandalkan proses PPDB manual, paper-based, dan status tracking yang kurang transparan.',
                'solution' => 'Platform PPDB end-to-end dengan online registration, document upload, verification workflow, admin dashboard, parent portal, dan public school website.',
                'key_features' => ['Online registration forms', 'Document verification workflow', 'Admin dashboard', 'Parent portal', 'Public school website'],
                'relevant_capability' => ['Web & Portal Development', 'QA Governance', 'Agile Delivery'],
                'business_impact' => ['Proses admission lebih terstruktur dan auditable', 'Transparansi real-time untuk orang tua', 'Beban admin berkurang melalui workflow otomatis', 'SIT/UAT documentation dan BAST handover tersedia'],
            ],
            [
                'subtitle' => 'Employee Self-Service & HR Operations',
                'challenge' => 'Tim HR mengelola attendance, leave, payroll, dan data karyawan lewat spreadsheet tanpa sistem terpusat.',
                'solution' => 'Mahya HRMS dengan employee self-service, manager approval workflow, HR admin dashboard, reporting, dan mobile-friendly interface.',
                'key_features' => ['Attendance & leave management', 'Payroll processing', 'Employee profiles', 'Approval workflows', 'Reporting dashboard'],
                'relevant_capability' => ['Custom Software Development', 'SaaS Platform', 'Operational Systems'],
                'business_impact' => ['Data HR terpusat dengan visibility real-time', 'Waktu proses manual berkurang signifikan', 'Employee experience meningkat lewat self-service access', 'Platform scalable untuk multi-entity deployment'],
            ],
            [
                'subtitle' => 'Health, Safety & Environment Digitalization',
                'challenge' => 'HSE compliance dan safety reporting masih tersebar di form manual, spreadsheet, dan channel komunikasi yang terpisah.',
                'solution' => 'Platform HSE untuk incident reporting, safety checklist, compliance dashboard, real-time alert, audit trail, dan role-based access.',
                'key_features' => ['Incident reporting & tracking', 'Safety checklist management', 'Compliance dashboard', 'Real-time alerts', 'Audit trail'],
                'relevant_capability' => ['Operational Systems', 'Custom Software Development', 'QA Governance'],
                'business_impact' => ['Incident response lebih cepat', 'Visibility compliance lebih baik untuk management', 'Risiko unreported incident berkurang', 'Dokumentasi audit-ready tersedia'],
            ],
            [
                'subtitle' => 'Residential Cash Management Platform',
                'challenge' => 'Komunitas perumahan mengelola iuran, biaya fasilitas, dan cash flow lewat collection manual serta pencatatan informal.',
                'solution' => 'WargaKas sebagai platform cash management dengan billing, payment tracking, financial dashboard, expense management, resident portal, dan admin reporting.',
                'key_features' => ['Resident billing & invoicing', 'Payment tracking', 'Financial dashboard', 'Expense management', 'Resident portal'],
                'relevant_capability' => ['Custom Software Development', 'Web & Portal Development', 'SaaS Platform'],
                'business_impact' => ['Keuangan komunitas lebih transparan dan auditable', 'Beban collection manual berkurang', 'Kepercayaan resident meningkat lewat payment visibility', 'Model dapat diskalakan ke banyak cluster'],
            ],
            [
                'subtitle' => 'Intelligent Talent Acquisition',
                'challenge' => 'Recruitment team menghadapi volume CV tinggi, screening tidak konsisten, dan time-to-hire yang lambat.',
                'solution' => 'AI recruitment platform untuk CV parsing, candidate scoring, job-fit ranking, automated shortlisting, interview scheduling, recruiter dashboard, dan analytics.',
                'key_features' => ['AI CV parsing & scoring', 'Job-fit ranking', 'Automated shortlisting', 'Interview scheduling', 'Recruiter dashboard'],
                'relevant_capability' => ['AI Technology & GenAI', 'Custom Software Development', 'SaaS Platform'],
                'business_impact' => ['Waktu CV screening dapat berkurang hingga 80%', 'Evaluasi kandidat lebih konsisten berbasis kriteria', 'Time-to-hire lebih cepat', 'Produktivitas recruiter dan candidate experience meningkat'],
            ],
            [
                'subtitle' => 'Personalized Learning & Performance Development',
                'challenge' => 'Organisasi kesulitan menghadirkan coaching yang konsisten dan scalable, terutama untuk distributed team.',
                'solution' => 'AI coaching platform dengan conversational AI, personalized learning path, goal setting, progress dashboard, manager visibility, content library, dan behavioral nudges.',
                'key_features' => ['AI coaching chatbot', 'Personalized learning paths', 'Goal setting & tracking', 'Progress dashboards', 'Manager visibility'],
                'relevant_capability' => ['AI Technology & GenAI', 'SaaS Platform Development', 'Custom Software Development'],
                'business_impact' => ['Coaching scalable tanpa biaya meningkat proporsional', 'Development journey personal untuk tiap employee', 'Engagement belajar meningkat lewat AI nudges', 'Manager dan HR mendapat visibility performa real-time'],
            ],
            [
                'subtitle' => 'Microsoft Dynamics 365 Capability Reference',
                'challenge' => 'Enterprise finance membutuhkan kontinuitas D365, support lokal yang responsif, dan jembatan antara capability Microsoft dengan kebutuhan bisnis Indonesia.',
                'solution' => 'D365 Finance configuration support, customization assistance, module implementation assistance, Power BI reporting, Power Automate workflow, AI Builder integration, user training, dan managed services.',
                'key_features' => ['D365 Finance module support', 'Power BI reporting integration', 'Power Automate workflow automation', 'AI Builder integration', 'User training & adoption support'],
                'relevant_capability' => ['Microsoft D365 & Power Platform', 'Managed Support', 'Technology Consulting'],
                'business_impact' => ['Response time lebih cepat dengan managed service model', 'Support lokal dengan backing Romulus Digital', 'Reporting dan automation lebih terhubung lewat Power Platform', 'Engagement fleksibel untuk project atau retainer support'],
            ],
        ],
        'team' => [
            'model_label' => 'Scalable Team Model',
            'model_title' => 'Tim inti fokus pada ownership, lalu kapasitas teknis diskalakan sesuai scope.',
            'model_body' => 'Engineer, designer, QA specialist, cloud specialist, dan Microsoft specialist dapat diaktifkan melalui partner network, RaaS model, dan freelancer ecosystem sesuai ukuran proyek.',
        ],
        'team_members' => [
            ['focus' => ['Client engagement', 'Strategy & sales', 'Project management', 'QA governance', 'Scrum facilitation', 'Delivery ownership']],
            ['focus' => ['Technology architecture', 'Engineering direction', 'System design', 'Code quality', 'Technical delivery']],
            ['focus' => ['Operations coordination', 'Stakeholder follow-up', 'Delivery administration', 'Internal process governance']],
        ],
        'engagement_details' => [
            ['title' => 'Discovery & Scoping', 'body' => 'Sesi discovery untuk memahami business challenge, goals, dan technical landscape.', 'output' => 'Output: project brief, scope document, dan solution proposal.'],
            ['title' => 'Design & Architecture', 'body' => 'Perancangan solution architecture, UX flow, dan technical blueprint.', 'output' => 'Output: wireframes, system design, dan delivery plan.'],
            ['title' => 'Agile Development & QA', 'body' => 'Build iteratif dengan Agile/Scrum, sprint review, SIT/UAT, dan quality gates.', 'output' => 'Output: working software, test reports, dan release documentation.'],
            ['title' => 'Handover, Support & Growth', 'body' => 'BAST handover, knowledge transfer, ongoing support, dan roadmap fase berikutnya.', 'output' => 'Output: BAST document, support SLA, dan improvement roadmap.'],
        ],
        'engagement_type_details' => [
            ['title' => 'Fixed Scope Project', 'body' => 'Cocok untuk kebutuhan dengan scope, timeline, dan deliverable yang sudah jelas.'],
            ['title' => 'Retainer Support', 'body' => 'Support berkala untuk maintenance, issue handling, dan improvement request.'],
            ['title' => 'Managed Services', 'body' => 'Model operasional jangka panjang untuk platform, D365, atau support digital.'],
            ['title' => 'Resource as a Service (RaaS)', 'body' => 'Akses kapasitas engineer, designer, QA, atau specialist sesuai kebutuhan proyek.'],
            ['title' => 'Strategic Advisory', 'body' => 'Pendampingan roadmap, AI readiness, architecture review, dan transformation planning.'],
        ],
        'contact' => [
            'email' => 'Email',
            'website' => 'Website',
            'availability' => 'Tersedia untuk meeting, demo, dan discovery call.',
        ],
    ],

    'en' => [
        'about_detail' => [
            'positioning_label' => 'About & Positioning',
            'positioning_title' => 'Local delivery with enterprise standards and regional backing.',
            'positioning_body' => [
                'Nakala Digital serves as an Indonesia-based delivery and client-facing partner for organizations that need AI technology, custom software development, and ready-to-use digital solutions.',
                'We combine enterprise-grade delivery standards with deep local market understanding, enabling products that are scalable, practical, and relevant to Indonesian operations.',
            ],
            'romulus_note' => 'Through a strategic partnership with Romulus Digital, Nakala Digital is backed by regional capabilities across AI SaaS, Microsoft D365, cloud applications, Experience-Led Design, and Resources as a Service.',
        ],
        'why_details' => [
            ['title' => 'Local Delivery, Regional Reach', 'body' => 'Indonesia-based team with direct regional technology support through the Romulus Digital partnership network.'],
            ['title' => 'AI-Enabled Mindset', 'body' => 'AI automation and intelligent workflows are embedded where they create real operational value.'],
            ['title' => 'Agile Delivery & QA Governance', 'body' => 'Sprint delivery, backlog management, SIT/UAT, documentation, and release gates are built into delivery.'],
            ['title' => 'Experience-Led Design', 'body' => 'Solutions are shaped from user journeys and business processes, not technology alone.'],
            ['title' => 'Practical & Impact-Driven', 'body' => 'Every solution is designed to be scalable, operable, and tied to measurable business outcomes.'],
            ['title' => 'Strategic Partner Network', 'body' => 'Engineering, design, QA, cloud, and Microsoft specialist capacity can scale based on project need.'],
        ],
        'service_pillar_details' => [
            ['title' => 'AI Technology & GenAI', 'body' => 'Intelligent automation, GenAI applications, AI-powered recruitment, coaching, and decision support systems.'],
            ['title' => 'Custom Software Development', 'body' => 'Web apps, mobile apps, SaaS platforms, and enterprise systems built to specification.'],
            ['title' => 'Technology Consulting', 'body' => 'Business and technology alignment, solution roadmaps, requirements, governance, and strategic advisory.'],
            ['title' => 'Web & Portal Development', 'body' => 'Corporate websites, CMS, e-commerce, public-facing portals, and education platforms.'],
            ['title' => 'QA Governance & Testing', 'body' => 'End-to-end QA, SIT/UAT, test planning, release governance, and acceptance documentation.'],
            ['title' => 'Managed Support & D365', 'body' => 'Post-launch support, Microsoft D365 Finance assistance, Power Platform, and managed services.'],
        ],
        'ai_capability_details' => [
            ['title' => 'GenAI Applications', 'body' => 'Conversational AI, document intelligence, and AI-assisted workflows using LLM technology.'],
            ['title' => 'AI Hiring & Recruitment', 'body' => 'CV parsing, candidate scoring, interview scheduling, talent analytics, and automated shortlisting.'],
            ['title' => 'AI Coaching Platforms', 'body' => 'Digital coaching assistants, personalized learning paths, goal tracking, and progress dashboards.'],
            ['title' => 'Intelligent Automation', 'body' => 'Process automation, smart notifications, and AI-driven operational triggers.'],
            ['title' => 'AI SaaS Platform Development', 'body' => 'End-to-end AI-powered SaaS product development for B2B and enterprise markets.'],
            ['title' => 'Data & Analytics Integration', 'body' => 'Dashboard intelligence, reporting automation, and data pipeline development.'],
            ['title' => 'Microsoft Power Platform', 'body' => 'Power BI, Power Automate, and AI Builder integration for enterprise clients.'],
            ['title' => 'Strategic AI Advisory', 'body' => 'AI readiness assessment, use case identification, and implementation roadmap.'],
        ],
        'solution_details' => [
            ['title' => 'Web Application Development', 'body' => 'Responsive, performant web apps built on modern frameworks with API-first architecture.'],
            ['title' => 'HRIS / HSE / Operational Platforms', 'body' => 'Custom HR, safety, and operations management platforms for Indonesian business environments.'],
            ['title' => 'School & Education Portals', 'body' => 'PPDB systems, academic portals, and digital school platforms for foundations and educational institutions.'],
            ['title' => 'API & System Integration', 'body' => 'Secure API integration layers connecting existing tools, third-party services, and legacy systems.'],
        ],
        'solution_highlights' => [
            'Customer Engagement & Customer Profiling',
            'Omnichannel Commerce: POS, WMS, OMS, Loyalty, and SAP Integration',
            'LMS & Parent Experience with AI Support',
            'MoneyKu - Accounting and Small Business Management',
            'VMS - Vendor Management System',
            'OSMS - Operational Security Management System',
            'Digital Cooperative and Local Government Solutions',
            'BGN / SPPG Operational Support',
            'HRMS and HSE Platforms',
            'Web Portal and WargaKas',
            'AI Hiring and Recruitment',
            'Digital Coaching and AI Coach Platform',
        ],
        'model_details' => [
            [
                'title' => 'Consulting & Strategy',
                'body' => 'Define transformation direction, solution architecture, user experience, and AI readiness before build begins.',
                'items' => [
                    'Technology consulting and digital transformation roadmaps',
                    'Experience-led design, UX research, wireframes, and product flows',
                    'AI readiness assessment and high-impact use case identification',
                ],
            ],
            [
                'title' => 'Build & Develop',
                'body' => 'Turn scope into usable digital products through software development, AI platforms, and operational systems.',
                'items' => [
                    'Custom software, web apps, mobile apps, SaaS, and enterprise systems',
                    'AI & GenAI platforms such as AI Hiring, AI Coaching, and document intelligence',
                    'Operational systems for HRMS, HSE, cash management, and industry needs',
                ],
            ],
            [
                'title' => 'Run & Support',
                'body' => 'Protect release quality and product continuity through QA governance, support, D365, and continuous improvement.',
                'items' => [
                    'SIT/UAT, release governance, test reports, and BAST documentation',
                    'Post-launch maintenance, bug fixing, and improvement requests',
                    'D365 Finance support, Power Platform integration, and Resources as a Service',
                ],
            ],
        ],
        'delivery_notes' => [
            ['title' => 'Delivery artifacts', 'body' => 'Product backlog, sprint plans, sprint review notes, SIT/UAT documentation, handover package, and BAST.'],
            ['title' => 'Continuous improvement', 'body' => 'Post-go-live retrospectives and structured improvement cycles ensure each iteration gets better.'],
        ],
        'qa_governance' => [
            ['title' => 'Requirement Review', 'body' => 'Functional and non-functional requirements are validated before development begins.'],
            ['title' => 'Test Planning & SIT/UAT', 'body' => 'Test cases, scenario coverage, and formal user acceptance testing are structured with clients.'],
            ['title' => 'Bug Tracking & Release Readiness', 'body' => 'Issue logging, severity classification, resolution tracking, and go/no-go release gates are managed clearly.'],
            ['title' => 'BAST, Handover & Warranty', 'body' => 'Acceptance documentation, knowledge transfer, and warranty support are prepared for production transition.'],
        ],
        'portfolio' => [
            'subtitle' => 'Detailed case studies from challenge to capability and impact.',
            'features' => 'Key Features',
            'capability' => 'Relevant Capability',
            'business_impact' => 'Business Impact',
        ],
        'portfolio_items' => [
            [
                'subtitle' => 'Education Digital Transformation',
                'challenge' => 'Educational institutions still rely on manual, paper-based admission processes with limited transparency and status tracking.',
                'solution' => 'An end-to-end PPDB platform with online registration, document upload, verification workflow, admin dashboard, parent portal, and public school website.',
                'key_features' => ['Online registration forms', 'Document verification workflow', 'Admin dashboard', 'Parent portal', 'Public school website'],
                'relevant_capability' => ['Web & Portal Development', 'QA Governance', 'Agile Delivery'],
                'business_impact' => ['More structured and auditable admission process', 'Real-time transparency for parents', 'Reduced admin workload through automated workflows', 'SIT/UAT documentation and BAST handover delivered'],
            ],
            [
                'subtitle' => 'Employee Self-Service & HR Operations',
                'challenge' => 'HR teams manage attendance, leave, payroll, and employee data manually across spreadsheets with no centralized system.',
                'solution' => 'Mahya HRMS with employee self-service, manager approval workflows, HR admin dashboard, reporting, and mobile-friendly interface.',
                'key_features' => ['Attendance & leave management', 'Payroll processing', 'Employee profiles', 'Approval workflows', 'Reporting dashboard'],
                'relevant_capability' => ['Custom Software Development', 'SaaS Platform', 'Operational Systems'],
                'business_impact' => ['Centralized HR data with real-time visibility', 'Significantly reduced manual HR processing time', 'Improved employee experience through self-service access', 'Scalable platform ready for multi-entity deployment'],
            ],
            [
                'subtitle' => 'Health, Safety & Environment Digitalization',
                'challenge' => 'HSE compliance and safety reporting are managed through manual forms, spreadsheets, and disconnected communication channels.',
                'solution' => 'A dedicated HSE platform for incident reporting, safety checklists, compliance dashboards, real-time alerts, audit trails, and role-based access.',
                'key_features' => ['Incident reporting & tracking', 'Safety checklist management', 'Compliance dashboard', 'Real-time alerts', 'Audit trail'],
                'relevant_capability' => ['Operational Systems', 'Custom Software Development', 'QA Governance'],
                'business_impact' => ['Faster incident response with digital reporting', 'Improved HSE compliance visibility for management', 'Reduced risk of unreported safety incidents', 'Audit-ready documentation and reporting trail'],
            ],
            [
                'subtitle' => 'Residential Cash Management Platform',
                'challenge' => 'Residential communities manage monthly dues, facility fees, and cash flow through manual collection and informal records.',
                'solution' => 'WargaKas as a cash management platform with billing, payment tracking, financial dashboards, expense management, resident portal, and admin reporting.',
                'key_features' => ['Resident billing & invoicing', 'Payment tracking', 'Financial dashboard', 'Expense management', 'Resident portal'],
                'relevant_capability' => ['Custom Software Development', 'Web & Portal Development', 'SaaS Platform'],
                'business_impact' => ['Transparent and auditable community financial management', 'Reduced manual collection effort', 'Improved resident trust through payment visibility', 'Scalable model for multiple residential clusters'],
            ],
            [
                'subtitle' => 'Intelligent Talent Acquisition',
                'challenge' => 'Recruitment teams face high CV volume, inconsistent screening, and slow time-to-hire.',
                'solution' => 'An AI recruitment platform for CV parsing, candidate scoring, job-fit ranking, automated shortlisting, interview scheduling, recruiter dashboard, and analytics.',
                'key_features' => ['AI CV parsing & scoring', 'Job-fit ranking', 'Automated shortlisting', 'Interview scheduling', 'Recruiter dashboard'],
                'relevant_capability' => ['AI Technology & GenAI', 'Custom Software Development', 'SaaS Platform'],
                'business_impact' => ['CV screening time can be reduced by up to 80%', 'More consistent candidate evaluation based on criteria', 'Faster time-to-hire', 'Improved recruiter productivity and candidate experience'],
            ],
            [
                'subtitle' => 'Personalized Learning & Performance Development',
                'challenge' => 'Organizations struggle to deliver consistent, scalable coaching, especially for distributed teams.',
                'solution' => 'An AI coaching platform with conversational AI, personalized learning paths, goal setting, progress dashboards, manager visibility, content library, and behavioral nudges.',
                'key_features' => ['AI coaching chatbot', 'Personalized learning paths', 'Goal setting & tracking', 'Progress dashboards', 'Manager visibility'],
                'relevant_capability' => ['AI Technology & GenAI', 'SaaS Platform Development', 'Custom Software Development'],
                'business_impact' => ['Scalable coaching delivery without proportional cost increase', 'Personalized development journeys for each employee', 'Improved learning engagement through AI nudges', 'Real-time performance visibility for managers and HR teams'],
            ],
            [
                'subtitle' => 'Microsoft Dynamics 365 Capability Reference',
                'challenge' => 'Enterprise finance teams need D365 continuity, responsive local support, and a bridge between Microsoft capability and Indonesian business needs.',
                'solution' => 'D365 Finance configuration support, customization assistance, module implementation assistance, Power BI reporting, Power Automate workflows, AI Builder integration, user training, and managed services.',
                'key_features' => ['D365 Finance module support', 'Power BI reporting integration', 'Power Automate workflow automation', 'AI Builder integration', 'User training & adoption support'],
                'relevant_capability' => ['Microsoft D365 & Power Platform', 'Managed Support', 'Technology Consulting'],
                'business_impact' => ['Faster response times through a managed service model', 'Local support backed by Romulus Digital', 'Reporting and automation connected through Power Platform', 'Flexible project-based or retainer support engagement'],
            ],
        ],
        'team' => [
            'model_label' => 'Scalable Team Model',
            'model_title' => 'The core team owns delivery while technical capacity scales by scope.',
            'model_body' => 'Engineers, designers, QA specialists, cloud specialists, and Microsoft specialists can be activated through the partner network, RaaS model, and freelancer ecosystem based on project scale.',
        ],
        'team_members' => [
            ['focus' => ['Client engagement', 'Strategy & sales', 'Project management', 'QA governance', 'Scrum facilitation', 'Delivery ownership']],
            ['focus' => ['Technology architecture', 'Engineering direction', 'System design', 'Code quality', 'Technical delivery']],
            ['focus' => ['Operations coordination', 'Stakeholder follow-up', 'Delivery administration', 'Internal process governance']],
        ],
        'engagement_details' => [
            ['title' => 'Discovery & Scoping', 'body' => 'A structured discovery session to understand business challenges, goals, and technical landscape.', 'output' => 'Output: project brief, scope document, and solution proposal.'],
            ['title' => 'Design & Architecture', 'body' => 'Solution architecture, UX flows, and technical blueprint are designed before build begins.', 'output' => 'Output: wireframes, system design, and delivery plan.'],
            ['title' => 'Agile Development & QA', 'body' => 'Iterative build using Agile/Scrum with sprint reviews, SIT/UAT, and quality gates.', 'output' => 'Output: working software, test reports, and release documentation.'],
            ['title' => 'Handover, Support & Growth', 'body' => 'BAST handover, knowledge transfer, ongoing support, and a roadmap for future phases.', 'output' => 'Output: BAST document, support SLA, and improvement roadmap.'],
        ],
        'engagement_type_details' => [
            ['title' => 'Fixed Scope Project', 'body' => 'Best for needs with clear scope, timeline, and deliverables.'],
            ['title' => 'Retainer Support', 'body' => 'Recurring support for maintenance, issue handling, and improvement requests.'],
            ['title' => 'Managed Services', 'body' => 'Long-term operational model for platforms, D365, or digital support.'],
            ['title' => 'Resource as a Service (RaaS)', 'body' => 'Access to engineers, designers, QA, or specialists based on project need.'],
            ['title' => 'Strategic Advisory', 'body' => 'Roadmap, AI readiness, architecture review, and transformation planning support.'],
        ],
        'contact' => [
            'email' => 'Email',
            'website' => 'Website',
            'availability' => 'Available for meetings, demos, and discovery calls.',
        ],
    ],
];
