<?php

return [
    'default_locale' => 'id',
    'public_url' => env('SITE_PUBLIC_URL', 'https://nakala.digital'),

    'locales' => [
        'id' => ['label' => 'ID', 'name' => 'Indonesia'],
        'en' => ['label' => 'EN', 'name' => 'English'],
    ],

    'brand' => [
        'name' => 'Nakala Digital',
        'logo' => 'assets/logo.svg',
        'logo_png' => 'assets/logo.png',
        'phone' => '+62 822 9570 6304',
        'email' => 'contact@nakala.digital',
        'website' => 'nakala.digital',
        'instagram' => '@nakala.digital',
        'location' => 'Pointlab Coworking Space, Graha Pos Indonesia, Jl. Banda No.30 Lantai 2 Blok C, Citarum, Bandung Wetan, Bandung City, West Java 40115',
        'contact_person' => 'Milzam Zihni',
        'contact_role' => 'Founder & CEO',
    ],

    'navigation' => [
        ['route' => 'home', 'icon' => 'home', 'labels' => ['id' => 'Beranda', 'en' => 'Home']],
        ['route' => 'about', 'icon' => 'info', 'labels' => ['id' => 'Tentang', 'en' => 'About']],
        ['route' => 'services', 'icon' => 'layers', 'labels' => ['id' => 'Layanan', 'en' => 'Services']],
        ['route' => 'delivery', 'icon' => 'check', 'labels' => ['id' => 'Delivery', 'en' => 'Delivery']],
        ['route' => 'portfolio', 'icon' => 'briefcase', 'labels' => ['id' => 'Portfolio', 'en' => 'Portfolio']],
        ['route' => 'team', 'icon' => 'users', 'labels' => ['id' => 'Tim', 'en' => 'Team']],
        ['route' => 'contact', 'icon' => 'phone', 'labels' => ['id' => 'Kontak', 'en' => 'Contact']],
    ],

    'pages' => [
        'home' => [
            'view' => 'pages.home',
            'route' => 'home',
            'changefreq' => 'weekly',
            'priority' => '1.0',
            'meta' => [
                'id' => [
                    'title' => 'Nakala Digital | Mitra AI & Software Development Indonesia',
                    'description' => 'Nakala Digital adalah mitra teknologi AI, software development, dan solusi digital berbasis Indonesia untuk transformasi bisnis.',
                    'keywords' => 'Nakala Digital, AI Indonesia, software development Indonesia, digital transformation',
                ],
                'en' => [
                    'title' => 'Nakala Digital | Indonesia AI & Software Development Partner',
                    'description' => 'Nakala Digital is an Indonesia-based AI technology, custom software development, and digital solutions partner for business transformation.',
                    'keywords' => 'Nakala Digital, AI technology Indonesia, software development Indonesia, digital transformation',
                ],
            ],
        ],
        'about' => [
            'view' => 'pages.about',
            'route' => 'about',
            'changefreq' => 'monthly',
            'priority' => '0.8',
            'meta' => [
                'id' => [
                    'title' => 'Tentang Nakala Digital | Mitra Delivery Digital Profesional',
                    'description' => 'Kenali Nakala Digital, filosofi brand, visi, misi, dan perannya sebagai mitra teknologi lokal dengan dukungan kapabilitas regional.',
                    'keywords' => 'tentang Nakala Digital, konsultan teknologi Indonesia, mitra digital, layanan AI Indonesia, pengembangan perangkat lunak, solusi digital, GenAI Indonesia, pengembangan web, portal sekolah, HRMS, layanan D365, QA governance, otomatisasi cerdas, transformasi digital, konsultan TI Bandung, software house Indonesia, pengembangan aplikasi kustom, integrasi API, layanan konsultasi teknologi, implementasi D365, dukungan terkelola',
                ],
                'en' => [
                    'title' => 'About Nakala Digital | Professional Digital Delivery Partner',
                    'description' => 'Learn about Nakala Digital, its brand philosophy, vision, mission, and role as a local technology delivery partner.',
                    'keywords' => 'about Nakala Digital, technology consulting Indonesia, digital delivery partner, AI services Indonesia, software development Indonesia, digital solutions, GenAI services, web portal development, HRMS, D365 managed services, QA governance, intelligent automation, digital transformation partner, Bandung software company, custom software development, API integration, technology consulting, enterprise web applications, managed support, product engineering',
                ],
            ],
        ],
        'services' => [
            'view' => 'pages.services',
            'route' => 'services',
            'changefreq' => 'monthly',
            'priority' => '0.9',
            'meta' => [
                'id' => [
                    'title' => 'Layanan | AI, Software Development, Portal Web & Managed Support',
                    'description' => 'Layanan Nakala Digital mencakup AI, GenAI, software development, web portal, sistem operasional, QA, D365, dan managed support.',
                    'keywords' => 'layanan AI Indonesia, GenAI, software development, web portal, D365 support',
                ],
                'en' => [
                    'title' => 'Services | AI, Software Development, Web Portals & Managed Support',
                    'description' => 'Explore Nakala Digital services including AI, GenAI, custom software, web portals, operational systems, QA, D365, and managed support.',
                    'keywords' => 'AI services Indonesia, GenAI development, custom software development, web portal development, D365 support',
                ],
            ],
        ],
        'delivery' => [
            'view' => 'pages.delivery',
            'route' => 'delivery',
            'changefreq' => 'monthly',
            'priority' => '0.7',
            'meta' => [
                'id' => [
                    'title' => 'Delivery & QA Governance | Nakala Digital',
                    'description' => 'Nakala Digital menggunakan agile delivery, sprint review, SIT, UAT, dokumentasi, BAST, dan QA governance untuk menjaga kualitas delivery.',
                    'keywords' => 'agile delivery Indonesia, QA governance, SIT UAT, software testing',
                ],
                'en' => [
                    'title' => 'Delivery & QA Governance | Nakala Digital',
                    'description' => 'Nakala Digital uses agile delivery, sprint review, SIT, UAT, documentation, BAST, and QA governance for delivery quality.',
                    'keywords' => 'agile delivery Indonesia, QA governance, SIT UAT, software testing',
                ],
            ],
        ],
        'portfolio' => [
            'view' => 'pages.portfolio',
            'route' => 'portfolio',
            'changefreq' => 'monthly',
            'priority' => '0.8',
            'meta' => [
                'id' => [
                    'title' => 'Portfolio & Studi Kasus | Nakala Digital',
                    'description' => 'Portfolio Nakala Digital meliputi portal sekolah, HRMS, HSE operations, AI hiring, AI coaching, dan D365 managed services.',
                    'keywords' => 'portfolio Nakala Digital, AI hiring platform, HRMS platform, portal sekolah',
                ],
                'en' => [
                    'title' => 'Portfolio & Case Studies | Nakala Digital',
                    'description' => 'Selected Nakala Digital portfolio across school portals, HRMS, HSE operations, AI hiring, AI coaching, and D365 managed services.',
                    'keywords' => 'Nakala Digital portfolio, AI hiring platform, HRMS platform, school portal',
                ],
            ],
        ],
        'team' => [
            'view' => 'pages.team',
            'route' => 'team',
            'changefreq' => 'monthly',
            'priority' => '0.6',
            'meta' => [
                'id' => [
                    'title' => 'Tim Inti | Leadership Nakala Digital',
                    'description' => 'Kenali tim inti Nakala Digital yang memimpin strategi, teknologi, dan operasional delivery.',
                    'keywords' => 'tim Nakala Digital, Milzam Zihni, Rinaldy Pasya, Raul Mahya Komaran',
                ],
                'en' => [
                    'title' => 'Core Team | Nakala Digital Leadership',
                    'description' => 'Meet the Nakala Digital core team leading strategy, technology, and delivery operations.',
                    'keywords' => 'Nakala Digital team, Milzam Zihni, Rinaldy Pasya, Raul Mahya Komaran',
                ],
            ],
        ],
        'contact' => [
            'view' => 'pages.contact',
            'route' => 'contact',
            'changefreq' => 'monthly',
            'priority' => '0.7',
            'meta' => [
                'id' => [
                    'title' => 'Kontak Nakala Digital | Bangun Masa Depan Digital Bersama',
                    'description' => 'Hubungi Nakala Digital di Bandung untuk AI technology, software development, managed support, dan strategic digital advisory.',
                    'keywords' => 'kontak Nakala Digital, software company Bandung, AI partner Indonesia',
                ],
                'en' => [
                    'title' => 'Contact Nakala Digital | Build The Future Together',
                    'description' => 'Contact Nakala Digital in Bandung for AI technology, software development, managed support, and strategic digital advisory.',
                    'keywords' => 'contact Nakala Digital, software company Bandung, AI technology partner Indonesia',
                ],
            ],
        ],
    ],

    'content' => [
        'id' => [
            'brand' => [
                'tagline' => 'Professional Delivery. Meaningful Solutions. Impactful Growth.',
                'description' => 'Mitra teknologi AI, software development, dan transformasi digital berbasis Indonesia.',
            ],
            'ui' => [
                'contact' => 'Kontak',
                'language' => 'Bahasa',
            ],
            'home' => [
                'eyebrow' => 'Mitra Teknologi AI Indonesia',
                'title' => 'Nakala Digital',
                'lead' => 'Kami membantu organisasi membangun solusi digital profesional, bermakna, dan berdampak melalui technology consulting, AI, software development, QA governance, dan delivery excellence.',
                'sticker' => 'INDONESIA TECH PARTNER',
                'small_label' => 'NO BORING DIGITAL SOLUTIONS',
                'cta_primary' => 'Mulai Diskusi',
                'cta_secondary' => 'Lihat Layanan',
                'panel' => ['AI Technology', 'Software Development', 'Digital Transformation'],
                'capabilities_label' => 'Kapabilitas Utama',
                'capabilities_title' => 'Solusi digital yang fokus pada kebutuhan bisnis.',
                'capabilities_body' => 'Nakala Digital menjadi mitra delivery lokal dan client-facing untuk organisasi di Indonesia, didukung kapabilitas regional Romulus Digital.',
                'philosophy_label' => 'Filosofi Brand',
                'philosophy_title' => 'Delivery profesional, solusi bermakna, pertumbuhan berdampak.',
                'why_label' => 'Mengapa Nakala Digital',
                'why_title' => 'Model kerja yang sederhana untuk delivery yang serius.',
            ],
            'about' => [
                'eyebrow' => 'Tentang Nakala Digital',
                'title' => 'Mitra lokal untuk AI, software, dan solusi digital.',
                'lead' => 'Nakala Digital adalah perusahaan teknologi berbasis Indonesia yang menghadirkan AI technology, custom software development, dan digital solutions.',
                'company_title' => 'Tentang perusahaan',
                'company_body' => [
                    'Kami menjadi mitra delivery lokal dan client-facing untuk organisasi di Indonesia.',
                    'Fokus kami adalah proses yang jelas, produk yang berguna, dan nilai operasional yang bisa diukur.',
                ],
                'vision_label' => 'Visi & Misi',
                'vision_title' => 'Kemitraan strategis untuk pertumbuhan organisasi.',
                'vision_body' => 'Menjadi mitra teknologi strategis yang menghadirkan solusi digital profesional, bermakna, dan berdampak bagi pertumbuhan organisasi di Indonesia dan pasar regional.',
            ],
            'services' => [
                'eyebrow' => 'Layanan',
                'title' => 'AI, software, portal web, operasional, QA, dan support.',
                'lead' => 'Layanan Nakala Digital dirancang agar mudah dipahami decision maker: dari konsultasi teknologi, AI, software development, portal, QA governance, sampai managed support.',
                'pillars_label' => 'Service Pillars',
                'pillars_title' => 'Kapabilitas yang saling terhubung.',
                'ai_label' => 'Kapabilitas AI',
                'ai_title' => 'AI yang praktis untuk lingkungan kerja nyata.',
                'ai_body' => 'Kami membantu organisasi mengidentifikasi, merancang, membangun, dan mengelola produk serta workflow berbasis AI.',
                'solutions_label' => 'Software & Digital Solutions',
                'solutions_title' => 'Sistem custom yang mengikuti proses bisnis.',
                'model_label' => 'Product & Solution Model',
                'model_title' => 'Konsultasi, bangun, jalankan, dan support.',
            ],
            'delivery' => [
                'eyebrow' => 'Delivery & QA',
                'title' => 'Agile delivery dengan kontrol kualitas yang jelas.',
                'lead' => 'Kami menggunakan checkpoint, sprint rhythm, SIT/UAT, dokumentasi, BAST, dan handover support untuk menjaga kualitas delivery.',
                'agile_label' => 'Agile Delivery',
                'agile_title' => 'Dari discovery sampai continuous improvement.',
                'qa_label' => 'QA Governance',
                'qa_title' => 'Kualitas delivery dijaga melalui checkpoint.',
            ],
            'portfolio' => [
                'eyebrow' => 'Portfolio',
                'title' => 'Pekerjaan terpilih di web, operasional, HR, AI, dan support.',
                'lead' => 'Setiap case dapat dijelaskan melalui challenge, solution, dan business impact.',
                'challenge' => 'Challenge',
                'solution' => 'Solution',
                'impact' => 'Impact',
            ],
            'team' => [
                'eyebrow' => 'Tim Inti',
                'title' => 'Leadership untuk strategi, teknologi, dan delivery.',
                'lead' => 'Nakala Digital dipimpin oleh tim inti yang fokus pada delivery profesional, kualitas teknis, dan hasil jangka panjang untuk klien.',
                'partners_label' => 'Partner Network',
                'partners_title' => 'Kapabilitas regional melalui partner terpercaya.',
            ],
            'contact' => [
                'eyebrow' => 'Kontak',
                'title' => 'Mari bangun masa depan digital bersama.',
                'lead' => 'Nakala Digital siap menjadi mitra teknologi berbasis Indonesia, dari diskusi awal sampai pertumbuhan digital jangka panjang.',
                'contact_person' => 'Contact Person',
                'phone' => 'Phone',
                'engagement_label' => 'Engagement Model',
                'engagement_title' => 'Client journey yang sederhana dan jelas.',
                'types_label' => 'Engagement Types',
                'types_title' => 'Cara kerja yang fleksibel.',
            ],
            'capabilities' => [
                ['title' => 'Technology Consulting', 'body' => 'Roadmap, arsitektur, digital maturity, dan advisory implementasi yang praktis.'],
                ['title' => 'Software Development', 'body' => 'Platform custom, portal, integrasi, sistem operasional, dan aplikasi web enterprise-ready.'],
                ['title' => 'AI Technology', 'body' => 'Produk GenAI, intelligent automation, integrasi analytics, dan workflow bisnis berbasis AI.'],
            ],
            'philosophy' => [
                ['title' => 'Professional Delivery', 'body' => 'Proses jelas, governance, dokumentasi, disiplin QA, dan akuntabilitas eksekusi.'],
                ['title' => 'Meaningful Solutions', 'body' => 'Menyelesaikan kebutuhan user dan bisnis melalui produk digital yang mudah digunakan.'],
                ['title' => 'Impactful Growth', 'body' => 'Memberikan nilai terukur, efisiensi operasional, dan pertumbuhan berkelanjutan.'],
            ],
            'mission' => [
                'Menghadirkan solusi dengan governance yang kuat',
                'Membangun produk digital yang bermakna',
                'Mendorong otomatisasi berbasis AI',
                'Membangun kemitraan jangka panjang',
                'Meningkatkan digital maturity organisasi',
            ],
            'why' => [
                'Local Delivery, Regional Reach',
                'AI-Enabled Mindset',
                'Agile Delivery & QA Governance',
                'Experience-Led Design',
                'Practical & Impact-Driven',
                'Strategic Partner Network',
            ],
            'service_pillars' => [
                'AI Technology & GenAI',
                'Custom Software Development',
                'Technology Consulting',
                'Web & Portal Development',
                'QA Governance & Testing',
                'Managed Support & D365',
            ],
            'ai_capabilities' => [
                'GenAI Applications',
                'AI Hiring & Recruitment',
                'AI Coaching Platforms',
                'Intelligent Automation',
                'AI SaaS Platform Development',
                'Data & Analytics Integration',
                'Microsoft Power Platform',
                'Strategic AI Advisory',
            ],
            'solutions' => [
                'Web Application Development',
                'HRIS / HSE Platforms',
                'School & Education Portals',
                'API & System Integration',
            ],
            'models' => [
                ['title' => 'Consulting & Strategy', 'items' => ['Technology Consulting', 'Experience-Led Design', 'AI Readiness Assessment']],
                ['title' => 'Build & Develop', 'items' => ['Custom Software Development', 'AI & GenAI Platforms', 'Operational Systems']],
                ['title' => 'Run & Support', 'items' => ['QA Governance', 'Managed Support', 'D365 & Power Platform']],
            ],
            'delivery_steps' => ['Discovery', 'Planning', 'Design', 'Development', 'Testing', 'Deployment', 'Continuous Improvement'],
            'qa_steps' => ['Requirement Review', 'Test Planning', 'SIT/UAT', 'Release Readiness', 'Bug Tracking', 'Handover', 'Warranty Support'],
            'portfolio_items' => [
                ['name' => 'Website PPDB & School Portal', 'challenge' => 'Proses penerimaan dan informasi sekolah membutuhkan journey digital yang lebih jelas.', 'solution' => 'Portal dengan alur registrasi, konten terstruktur, dan dukungan admin.', 'impact' => 'Akses lebih baik untuk siswa, orang tua, dan tim sekolah.'],
                ['name' => 'Mahya HRMS Platform', 'challenge' => 'Operasional HR membutuhkan visibilitas dan kontrol data karyawan.', 'solution' => 'Workflow absensi, data karyawan, approval, dan reporting.', 'impact' => 'Operasional HR lebih efisien dan laporan lebih jelas.', 'image' => 'assets/portfolio/mahya-hrms.png'],
                ['name' => 'HSE Operations Platform', 'challenge' => 'Workflow safety membutuhkan struktur, tracking, dan reporting.', 'solution' => 'Incident tracking, form, approval, dan dashboard visibility.', 'impact' => 'Compliance dan kontrol operasional lebih kuat.'],
                ['name' => 'WargaKas', 'challenge' => 'Keuangan komunitas membutuhkan pencatatan dan transparansi sederhana.', 'solution' => 'Pencatatan kas, akses anggota, dan laporan keuangan.', 'impact' => 'Operasional keuangan komunitas lebih jelas.', 'image' => 'assets/portfolio/wargakas.png'],
                ['name' => 'AI Hiring Platform', 'challenge' => 'Screening kandidat membutuhkan evaluasi yang lebih cepat dan terstruktur.', 'solution' => 'AI-assisted matching, workflow recruitment, dan hiring insights.', 'impact' => 'Proses hiring lebih cepat dengan decision support yang lebih baik.', 'images' => ['assets/portfolio/iassess.png', 'assets/portfolio/beecruit.png']],
                ['name' => 'Digital Coaching / AI Coach Platform', 'challenge' => 'Coaching perlu scalable tanpa kehilangan personalisasi.', 'solution' => 'Personalized prompts, coaching journey, dan progress tracking.', 'impact' => 'Dukungan learning dan development bisa berjalan lebih luas.', 'image' => 'assets/portfolio/ai-coach.png'],
                ['name' => 'D365 Finance Support & Managed Services', 'challenge' => 'Operasional finance membutuhkan kontinuitas platform yang stabil.', 'solution' => 'Issue handling, improvement request, dan managed support.', 'impact' => 'Support enterprise finance lebih stabil dan terjaga.'],
                ['name' => 'Platform Customer Engagement 360°', 'challenge' => 'Enterprise membutuhkan modernisasi sistem operasional untuk interaksi pelanggan yang seamless di channel online dan offline.', 'solution' => 'Platform digital yang mencakup sistem POS, kiosk, e-commerce, front desk, serta modul CRM dan Finance.', 'impact' => 'Skalabilitas, efisiensi operasional, dan dampak bisnis dengan framework Microsoft Business Applications.', 'image' => 'assets/portfolio/360-customer-engagement.png'],
            ],
            'team_members' => [
                ['name' => 'Milzam Zihni', 'role' => 'Founder & CEO', 'initials' => 'MZ'],
                ['name' => 'Rinaldy Pasya', 'role' => 'Chief Technology Officer', 'initials' => 'RP'],
                ['name' => 'Raul Mahya Komaran', 'role' => 'Chief Operating Officer', 'initials' => 'RK'],
            ],
            'engagement' => ['Discovery & Scoping', 'Design & Architecture', 'Agile Development & QA', 'Handover, Support & Growth'],
            'engagement_types' => ['Fixed Scope Project', 'Retainer Support', 'Managed Services', 'Resource as a Service (RaaS)', 'Strategic Advisory'],
            'partners' => ['Romulus Digital', 'NCS Group', 'CloudMile'],
        ],

        'en' => [
            'brand' => [
                'tagline' => 'Professional Delivery. Meaningful Solutions. Impactful Growth.',
                'description' => 'Indonesia-based AI technology, software development, and digital transformation partner.',
            ],
            'ui' => [
                'contact' => 'Contact',
                'language' => 'Language',
            ],
            'home' => [
                'eyebrow' => 'Indonesia AI Technology Partner',
                'title' => 'Nakala Digital',
                'lead' => 'We help organizations build professional, meaningful, and impactful digital solutions through technology consulting, AI, software development, QA governance, and delivery excellence.',
                'sticker' => 'INDONESIA TECH PARTNER',
                'small_label' => 'NO BORING DIGITAL SOLUTIONS',
                'cta_primary' => 'Start a Conversation',
                'cta_secondary' => 'View Services',
                'panel' => ['AI Technology', 'Software Development', 'Digital Transformation'],
                'capabilities_label' => 'Core Capabilities',
                'capabilities_title' => 'Digital solutions focused on business needs.',
                'capabilities_body' => 'Nakala Digital serves as a local delivery and client-facing technology partner for organizations across Indonesia, backed by Romulus Digital regional capabilities.',
                'philosophy_label' => 'Brand Philosophy',
                'philosophy_title' => 'Professional delivery, meaningful solutions, impactful growth.',
                'why_label' => 'Why Nakala Digital',
                'why_title' => 'A simple partner model for serious delivery.',
            ],
            'about' => [
                'eyebrow' => 'About Nakala Digital',
                'title' => 'Local partner for AI, software, and digital solutions.',
                'lead' => 'Nakala Digital is an Indonesia-based technology company delivering AI technology, custom software development, and digital solutions.',
                'company_title' => 'About the company',
                'company_body' => [
                    'We serve as a local delivery and client-facing technology partner for organizations across Indonesia.',
                    'Our work focuses on clear process, useful products, and measurable operational value.',
                ],
                'vision_label' => 'Vision & Mission',
                'vision_title' => 'Strategic partnership for organizational growth.',
                'vision_body' => 'To become a strategic technology partner that delivers professional, meaningful, and impactful digital solutions for organizational growth in Indonesia and the regional market.',
            ],
            'services' => [
                'eyebrow' => 'Services',
                'title' => 'AI, software, web portals, operations, QA, and support.',
                'lead' => 'Nakala Digital services are designed for clear business decision-making: from technology consulting, AI, software development, portals, QA governance, to managed support.',
                'pillars_label' => 'Service Pillars',
                'pillars_title' => 'Connected capability for enterprise needs.',
                'ai_label' => 'AI Capabilities',
                'ai_title' => 'Practical AI for real working environments.',
                'ai_body' => 'We help organizations identify, design, build, and govern AI-enabled products and workflows.',
                'solutions_label' => 'Software & Digital Solutions',
                'solutions_title' => 'Custom systems built around business operations.',
                'model_label' => 'Product & Solution Model',
                'model_title' => 'Consult, build, run, and support.',
            ],
            'delivery' => [
                'eyebrow' => 'Delivery & QA',
                'title' => 'Agile delivery with clear quality control.',
                'lead' => 'We use checkpoints, sprint rhythm, SIT/UAT, documentation, BAST, and handover support to protect delivery quality.',
                'agile_label' => 'Agile Delivery',
                'agile_title' => 'From discovery to continuous improvement.',
                'qa_label' => 'QA Governance',
                'qa_title' => 'Delivery quality managed through checkpoints.',
            ],
            'portfolio' => [
                'eyebrow' => 'Portfolio',
                'title' => 'Selected work across web, operations, HR, AI, and support.',
                'lead' => 'Each case can be framed around the challenge, solution, and business impact.',
                'challenge' => 'Challenge',
                'solution' => 'Solution',
                'impact' => 'Impact',
            ],
            'team' => [
                'eyebrow' => 'Core Team',
                'title' => 'Leadership for strategy, technology, and delivery.',
                'lead' => 'Nakala Digital is led by a core team focused on professional delivery, technical quality, and long-term client outcomes.',
                'partners_label' => 'Partner Network',
                'partners_title' => 'Regional capability through trusted partners.',
            ],
            'contact' => [
                'eyebrow' => 'Contact',
                'title' => 'Let us build the digital future together.',
                'lead' => 'Nakala Digital is ready to be your Indonesia-based technology partner, from first conversation to long-term digital growth.',
                'contact_person' => 'Contact Person',
                'phone' => 'Phone',
                'engagement_label' => 'Engagement Model',
                'engagement_title' => 'A simple and clear client journey.',
                'types_label' => 'Engagement Types',
                'types_title' => 'Flexible ways to work together.',
            ],
            'capabilities' => [
                ['title' => 'Technology Consulting', 'body' => 'Roadmap, architecture, digital maturity, and practical implementation advisory.'],
                ['title' => 'Software Development', 'body' => 'Custom platforms, portals, integrations, operational systems, and enterprise-ready web applications.'],
                ['title' => 'AI Technology', 'body' => 'GenAI products, intelligent automation, analytics integration, and AI-enabled business workflows.'],
            ],
            'philosophy' => [
                ['title' => 'Professional Delivery', 'body' => 'Clear process, governance, documentation, QA discipline, and execution accountability.'],
                ['title' => 'Meaningful Solutions', 'body' => 'Solving real user and business problems through usable digital products.'],
                ['title' => 'Impactful Growth', 'body' => 'Delivering measurable value, operational efficiency, and sustainable growth.'],
            ],
            'mission' => [
                'Deliver solutions with strong governance',
                'Build meaningful digital products',
                'Enable AI-powered automation',
                'Create long-term partnerships',
                'Grow digital maturity across organizations',
            ],
            'why' => [
                'Local Delivery, Regional Reach',
                'AI-Enabled Mindset',
                'Agile Delivery & QA Governance',
                'Experience-Led Design',
                'Practical & Impact-Driven',
                'Strategic Partner Network',
            ],
            'service_pillars' => [
                'AI Technology & GenAI',
                'Custom Software Development',
                'Technology Consulting',
                'Web & Portal Development',
                'QA Governance & Testing',
                'Managed Support & D365',
            ],
            'ai_capabilities' => [
                'GenAI Applications',
                'AI Hiring & Recruitment',
                'AI Coaching Platforms',
                'Intelligent Automation',
                'AI SaaS Platform Development',
                'Data & Analytics Integration',
                'Microsoft Power Platform',
                'Strategic AI Advisory',
            ],
            'solutions' => [
                'Web Application Development',
                'HRIS / HSE Platforms',
                'School & Education Portals',
                'API & System Integration',
            ],
            'models' => [
                ['title' => 'Consulting & Strategy', 'items' => ['Technology Consulting', 'Experience-Led Design', 'AI Readiness Assessment']],
                ['title' => 'Build & Develop', 'items' => ['Custom Software Development', 'AI & GenAI Platforms', 'Operational Systems']],
                ['title' => 'Run & Support', 'items' => ['QA Governance', 'Managed Support', 'D365 & Power Platform']],
            ],
            'delivery_steps' => ['Discovery', 'Planning', 'Design', 'Development', 'Testing', 'Deployment', 'Continuous Improvement'],
            'qa_steps' => ['Requirement Review', 'Test Planning', 'SIT/UAT', 'Release Readiness', 'Bug Tracking', 'Handover', 'Warranty Support'],
            'portfolio_items' => [
                ['name' => 'Website PPDB & School Portal', 'challenge' => 'Admissions and school information needed a clearer digital journey.', 'solution' => 'A portal with registration flow, structured content, and admin support.', 'impact' => 'Better access for students, parents, and school teams.'],
                ['name' => 'Mahya HRMS Platform', 'challenge' => 'HR operations needed better visibility and employee data control.', 'solution' => 'Attendance, employee records, approvals, and reporting workflows.', 'impact' => 'More efficient HR operations and clearer reporting.', 'image' => 'assets/portfolio/mahya-hrms.png'],
                ['name' => 'HSE Operations Platform', 'challenge' => 'Safety workflows needed structure, tracking, and reporting.', 'solution' => 'Incident tracking, forms, approvals, and dashboard visibility.', 'impact' => 'Stronger compliance and operational control.'],
                ['name' => 'WargaKas', 'challenge' => 'Community finance needed simple records and transparency.', 'solution' => 'Cash flow recording, member access, and reporting tools.', 'impact' => 'Clearer financial operations for local communities.', 'image' => 'assets/portfolio/wargakas.png'],
                ['name' => 'AI Hiring Platform', 'challenge' => 'Candidate screening required faster structured evaluation.', 'solution' => 'AI-assisted matching, recruitment workflow support, and hiring insights.', 'impact' => 'Faster hiring process with better decision support.', 'images' => ['assets/portfolio/iassess.png', 'assets/portfolio/beecruit.png']],
                ['name' => 'Digital Coaching / AI Coach Platform', 'challenge' => 'Coaching needed to scale without losing personalization.', 'solution' => 'Personalized prompts, coaching journeys, and progress tracking.', 'impact' => 'Scalable support for learning and professional development.', 'image' => 'assets/portfolio/ai-coach.png'],
                ['name' => 'D365 Finance Support & Managed Services', 'challenge' => 'Finance operations needed reliable platform continuity.', 'solution' => 'Issue handling, improvement requests, and managed support.', 'impact' => 'Stable support for enterprise finance operations.'],
                ['name' => '360° Customer Engagement Platform', 'challenge' => 'An enterprise needed to modernize systems and enable seamless user engagement across online and offline channels.', 'solution' => 'An integrated platform featuring POS systems, kiosks, web e-commerce, and front desk services with CRM and Finance modules.', 'impact' => 'Scalability, operational efficiency, and long-term impact built on Microsoft Business Applications.', 'image' => 'assets/portfolio/360-customer-engagement.png'],
            ],
            'team_members' => [
                ['name' => 'Milzam Zihni', 'role' => 'Founder & CEO', 'initials' => 'MZ'],
                ['name' => 'Rinaldy Pasya', 'role' => 'Chief Technology Officer', 'initials' => 'RP'],
                ['name' => 'Raul Mahya Komaran', 'role' => 'Chief Operating Officer', 'initials' => 'RK'],
            ],
            'engagement' => ['Discovery & Scoping', 'Design & Architecture', 'Agile Development & QA', 'Handover, Support & Growth'],
            'engagement_types' => ['Fixed Scope Project', 'Retainer Support', 'Managed Services', 'Resource as a Service (RaaS)', 'Strategic Advisory'],
            'partners' => ['Romulus Digital', 'NCS Group', 'CloudMile'],
        ],
    ],
];
